### PR TITLE
add brainhack AustraliaAsia

### PR DESCRIPTION
**Pull request by likeajumprope**
closes issue #39. Works when I serve it locally.

### CODE REVIEW

**Comment by likeajumprope** [comment]
@Remi-Gau please review

**Review by Remi-Gau — COMMENTED** [review]
looks good but I think the number of files changed should be higher than that if you ran the genrate events page script:

https://github.com/brainhackorg/global2023/blob/main/CONTRIBUTING.md#procedure

did you only commit a subset of the changes?

**Comment by likeajumprope** [comment]
indeed, there were a lot of changes to a lot of index.md files - is that what you mean? I have pushed those now as well.

**Review by Remi-Gau — APPROVED** [review]

**Comment by Remi-Gau** [comment]
ok good to go

**Pull request merged**
